server:
  port: 8761
eureka:
  instance:
    hostname: eureke-server #主机名
  client:
    register-with-eureka: false #不注册自己到eureka
    fetch-registry: false #不从eureka尚获取服务注册信息
    service-url:
      defaultZone: http://localhost:8761/eureka/